In [80]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [81]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [82]:
prac_data=pd.read_csv('/content/drive/MyDrive/Machine learning files/datasets/messy_medical_data.csv')
prac_data

,Age,Sex,BMI,Children,Smoker,Region,Cholesterol,BP,Charges
0,19,MALE,27.900,0,YES,southwest,180,120/80,$16884.92
1,18,female,33.770,1,no,Southeast,150,110/70,1725.55
2,28,M,33.000,3,No,southeast,200mg,130/85,4449.46
3,33,male,22.705,0,NO,northwest,170,120/80,21984.47
4,32,M,28.880,0,no,northwest,210,140/90,3866.86
5,31,F,25.740,0,no,southeast,160,110/75,3756.62
6,46,female,33.440,1,no,southeast,190,130/80,8240.59
7,37,F,27.740,3,no,northwest,180,120/70,7281.51

In [83]:
prac_data['Sex'].unique()

array(['MALE', 'female', 'M', 'male', 'F'], dtype=object)

In [84]:
prac_data['Sex']=prac_data['Sex'].str.replace('M','male')
prac_data['Sex']=prac_data['Sex'].str.replace('F','female')
prac_data['Sex']=prac_data['Sex'].str.replace('MALE','male')
prac_data['Sex']=prac_data['Sex'].map({'female':1,'male':0})
prac_data['Sex']=prac_data['Sex'].astype(float)

In [85]:
prac_data['Smoker'].unique()

array(['YES', 'no', 'No', 'NO'], dtype=object)

In [86]:
prac_data['Smoker']=prac_data['Smoker'].str.replace('no','NO')
prac_data['Smoker']=prac_data['Smoker'].str.replace('No','NO')
prac_data['Smoker']=prac_data['Smoker'].map({'YES':1,'NO':0})

In [87]:
prac_data=prac_data.drop('Region',axis=1)
prac_data=prac_data.drop('BP',axis=1)

In [88]:
prac_data

   Age  Sex     BMI  Children  Smoker Cholesterol    Charges
0   19  NaN  27.900         0       1         180  $16884.92
1   18  1.0  33.770         1       0         150    1725.55
2   28  0.0  33.000         3       0       200mg    4449.46
3   33  0.0  22.705         0       0         170   21984.47
4   32  0.0  28.880         0       0         210    3866.86
5   31  1.0  25.740         0       0         160    3756.62
6   46  1.0  33.440         1       0         190    8240.59
7   37  1.0  27.740         3       0         180    7281.51

In [89]:
prac_data['Cholesterol']=prac_data['Cholesterol'].str.replace('200mg','200').astype(float)
prac_data['Charges']=prac_data['Charges'].str.replace('$16884.92','16884.92').astype(float)

In [90]:
prac_data

   Age  Sex     BMI  Children  Smoker  Cholesterol   Charges
0   19  NaN  27.900         0       1        180.0  16884.92
1   18  1.0  33.770         1       0        150.0   1725.55
2   28  0.0  33.000         3       0        200.0   4449.46
3   33  0.0  22.705         0       0        170.0  21984.47
4   32  0.0  28.880         0       0        210.0   3866.86
5   31  1.0  25.740         0       0        160.0   3756.62
6   46  1.0  33.440         1       0        190.0   8240.59
7   37  1.0  27.740         3       0        180.0   7281.51

In [91]:
prac_data.dropna(inplace=True)

In [92]:
prac_data.shape

(7, 7)

In [93]:
y=prac_data.iloc[:,6:]
y

    Charges
1   1725.55
2   4449.46
3  21984.47
4   3866.86
5   3756.62
6   8240.59
7   7281.51

In [94]:
prac_data=prac_data.drop('Charges',axis=1)

In [95]:
x=prac_data.iloc[:,0:]
x

   Age  Sex     BMI  Children  Smoker  Cholesterol
1   18  1.0  33.770         1       0        150.0
2   28  0.0  33.000         3       0        200.0
3   33  0.0  22.705         0       0        170.0
4   32  0.0  28.880         0       0        210.0
5   31  1.0  25.740         0       0        160.0
6   46  1.0  33.440         1       0        190.0
7   37  1.0  27.740         3       0        180.0

In [96]:
prac_data.shape

(7, 6)

In [97]:
x_train,x_temp,y_train,y_temp=train_test_split(x,y,test_size=0.2,random_state=42)
x_dev,x_test,y_dev,y_test=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42)

In [98]:
scaler1=StandardScaler()
x_train_scaled=scaler1.fit_transform(x_train)
x_dev_scaled=scaler1.transform(x_dev)
x_test_scaled=scaler1.transform(x_test)

In [99]:
scaler2=StandardScaler()
y_train_scaled=scaler2.fit_transform(y_train)
y_dev_scaled=scaler2.transform(y_dev)
y_test_scaled=scaler2.transform(y_test)

In [100]:
x_train_scaled.shape

(5, 6)

In [101]:
#np.random.seed(0)

layer1_w=np.random.randn(10,6)*np.sqrt(2.0/x_train_scaled.shape[1])  #first layer weights
layer1_b=np.zeros((1,10))   #first layer bias

layer2_w=np.random.randn(20,10)*np.sqrt(2.0/x_train_scaled.shape[1]) #second layer weights
layer2_b=np.zeros((1,20))  #second layer bias

layer3_w=np.random.randn(10,20)*np.sqrt(2.0/x_train_scaled.shape[1]) #layer 3 weights
layer3_b=np.zeros((1,10)) # third layer bias

output_w=np.random.randn(1,10)*np.sqrt(2.0/x_train_scaled.shape[1])   #output neuron weights
output_b=np.zeros((1,1))  #output neuron bias

learning_rate=0.001  #learning rate

batch_size=x_train_scaled.shape[0] #batch size

reg_lambda=0.001

In [102]:
np.random.seed(42)

for epoch in range(1000):

  z1=np.dot(x_train_scaled,layer1_w.T)+layer1_b #foward pass
  a1=np.maximum(0,z1)  #activation function
  relu_grad1=(z1>0).astype(float)  #relu gradient
  layer1_norm2=np.linalg.norm(layer1_w,ord=2)  #layer 1 norm


  z2=np.dot(a1,layer2_w.T)+layer2_b #foward pass
  a2=np.maximum(0,z2)  #activation function
  relu_grad2=(z2>0).astype(float) #relu gradinet
  layer2_norm2=np.linalg.norm(layer2_w,ord=2) #layer 2 norm


  z3=np.dot(a2,layer3_w.T)+layer3_b  #foward pass
  a3=np.maximum(0,z3)   #activation function
  relu_grad3=(z3>0).astype(float)  #relu gradient
  layer3_norm2=np.linalg.norm(layer3_w,ord=2)  #layer 3 norm


  z4=np.dot(a3,output_w.T)+output_b #forwad pass
  a4=z4  #linear activation
  output_norm=np.linalg.norm(output_w,ord=2) #output neuron norm

  loss=0.5*(y_train_scaled-a4)**2  #losss function
  l2_penalty=(reg_lambda)/(2*batch_size)*(np.sum(layer1_w**2)+np.sum(layer2_w**2)+np.sum(layer3_w**2)+np.sum(output_w**2))
  loss=loss+l2_penalty

  #erros
  delta_output=a4-y_train_scaled  #output neuron error
  delta_layer3=np.dot(delta_output,output_w)*relu_grad3  #layer3 error
  delta_layer2=np.dot(delta_layer3,layer3_w)*relu_grad2  #layer2 error
  delta_layer1=np.dot(delta_layer2,layer2_w)*relu_grad1  #layer1 error


  #bias gradient
  output_b_grad=np.mean(delta_output,axis=0,keepdims=True)
  layer3_b_grad=np.mean(delta_layer3,axis=0,keepdims=True)
  layer2_b_grad=np.mean(delta_layer2,axis=0,keepdims=True)
  layer1_b_grad=np.mean(delta_layer1,axis=0,keepdims=True)

  #weight gradient
  output_w_grad=np.dot(delta_output.T,a3)/batch_size + (reg_lambda/batch_size)*output_w
  layer3_w_grad=np.dot(delta_layer3.T,a2)/batch_size + (reg_lambda/batch_size)*layer3_w
  layer2_w_grad=np.dot(delta_layer2.T,a1)/batch_size + (reg_lambda/batch_size)*layer2_w
  layer1_w_grad=np.dot(delta_layer1.T,x_train_scaled)/batch_size+(reg_lambda/batch_size)*layer1_w

  #update
  #output neuron
  output_w=output_w-learning_rate*output_w_grad
  output_b=output_b-learning_rate*output_b_grad

  #layer3
  layer3_w=layer3_w-learning_rate*layer3_w_grad
  layer3_b=layer3_b-learning_rate*layer3_b_grad

  #layer2
  layer2_w=layer2_w-learning_rate*layer2_w_grad
  layer2_b=layer2_b-learning_rate*layer2_b_grad

  #layer1
  layer1_w=layer1_w-learning_rate*layer1_w_grad
  layer1_b=layer1_b-learning_rate*layer1_b_grad


  if epoch %100==0:
    print(f'epoch:{epoch}, loss:{loss.mean().item():.2f},  norm_layer1:{layer1_norm2},  norm_layer2:{layer2_norm2}, norm_layer3:{layer3_norm2}, output_neuron:{output_norm}')

epoch:0, loss:1.03,  norm_layer1:2.6169609226721615,  norm_layer2:4.131764762669124, norm_layer3:3.717902704274233, output_neuron:1.416833734012578
epoch:100, loss:0.24,  norm_layer1:2.616482119848603,  norm_layer2:4.130993906995719, norm_layer3:3.71226952742961, output_neuron:1.4077119497732815
epoch:200, loss:0.15,  norm_layer1:2.617399668414969,  norm_layer2:4.1313199745575, norm_layer3:3.7104754979467094, output_neuron:1.4158833323808167
epoch:300, loss:0.10,  norm_layer1:2.617156552810546,  norm_layer2:4.130993482934073, norm_layer3:3.7090636837624578, output_neuron:1.4257109846123157
epoch:400, loss:0.06,  norm_layer1:2.616391600661276,  norm_layer2:4.130366330365712, norm_layer3:3.707877643180631, output_neuron:1.4353683726305444
epoch:500, loss:0.04,  norm_layer1:2.6154739689084257,  norm_layer2:4.129603769055982, norm_layer3:3.70694618350994, output_neuron:1.4438691998035986
epoch:600, loss:0.03,  norm_layer1:2.614831284455682,  norm_layer2:4.12904911785296, norm_layer3:3.7062580161737086, output_neuron:1.4506025927289576
epoch:700, loss:0.02,  norm_layer1:2.6144069206393814,  norm_layer2:4.128620441489319, norm_layer3:3.7057591270130192, output_neuron:1.4555615251497336
epoch:800, loss:0.02,  norm_layer1:2.614137340880338,  norm_layer2:4.128286921545239, norm_layer3:3.705397964899622, output_neuron:1.4590342616232526
epoch:900, loss:0.02,  norm_layer1:2.613962549790624,  norm_layer2:4.1280235659852735, norm_layer3:3.7051331778993424, output_neuron:1.461386729024307

network testing

In [103]:
print(layer1_w[0,0])

0.23542702215650654

In [104]:
z1=np.dot(x_dev_scaled,layer1_w.T)+layer1_b
a1=np.maximum(0,z1)
z2=np.dot(a1,layer2_w.T)+layer2_b
a2=np.maximum(0,z2)
z3=np.dot(a2,layer3_w.T)+layer3_b
a3=np.maximum(0,z3)
z4=np.dot(a3,output_w.T)+output_b
a4=z4
loss=0.5*(z4-y_dev_scaled)**2
loss.item()

1.1733003423318151

In [105]:
z1=np.dot(x_test_scaled,layer1_w.T)+layer1_b
a1=np.maximum(0,z1)
z2=np.dot(a1,layer2_w.T)+layer2_b
a2=np.maximum(0,z2)
z3=np.dot(a2,layer3_w.T)+layer3_b
a3=np.maximum(0,z3)
z4=np.dot(a3,output_w.T)+output_b
a4=z4
loss=0.5*(z4-y_test_scaled)**2
loss.item()

1.519869572796935

In [106]:
print(layer1_w[0, 0])

0.23542702215650654